---
- hosts: all
  sudo: yes
  vars:
    mount_dir: /vol/data
  tasks:
    - name: add arangodb key
      apt_key: url=https://www.arangodb.com/repositories/arangodb2/xUbuntu_14.04/Release.key state=present validate_certs=no
    - name: add arangodb repo
      apt_repository: repo='deb https://www.arangodb.com/repositories/arangodb2/xUbuntu_14.04 /' state=present
    - name: install arangodb
      apt: name='arangodb=2.5.0' update_cache=yes
    - name: create arangodb standalone folder
      file: path={{mount_dir}}/standalone state=directory owner=arangodb group=arangodb
    - name: create arangodb cluster folder
      file: path={{mount_dir}}/cluster state=directory owner=arangodb group=arangodb
    - name: Create a cluster Config file
      template: src=templates/arangod.dispatcher.conf.j2 dest=/etc/arangodb/arangod.conf
    - name: enable dispatcher kickstarter
      ini_file: dest=/etc/anotherconf
                section=dispatcher
                option=disable-dispatcher-kickstarter
                value=no
      notify:
      - restart arangodb
    - name: enable dispatcher frontend
      ini_file: dest=/etc/anotherconf
                section=dispatcher
                option=disable-dispatcher-frontend
                value=no
      notify:
      - restart arangodb
    - name: make sure arangodb uses upgraded db folder
      command: service arangodb upgrade
      notify:
      - restart arangodb
    - name: ensure arangodb is running
      service: name=arangodb state=started
#    - name: Remove authorized keys from user ubuntu
#      command: rm /home/ubuntu/.ssh/authorized_keys
#    - name: Remove authorized keys from user root
#      command: rm /root/.ssh/authorized_keys
  handlers:
    - name: restart arangodb
      service: name=arangodb state=restarted
